### ISSUE TITLE
fix routing error handling 

### ISSUE THREAD

**Issue by Julius-crt** [AryehSchoefer/SkSy-Hausaufgabe-2#2]
Muss noch schauen, mit welcher best practise man mit fehlern bei den Routen umgeht. To be continued

**Comment by AryehSchoefer** [comment]
Da du schon express-async-handler installiert hast, sollte dieser Artikel dir sehr helfen: https://zellwk.com/blog/express-errors/

**Comment by Julius-crt** [comment]
Stimmt express-async-handler kümmert sich ja wirklich automatisch einfach um jeden geworfenenen error
